version: "3.8"

services:
  app:
    build: .
    container_name: php_app
    ports:
      - "8080:80"  # acessa no navegador via localhost:8080
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controleestoque
      MYSQL_DATABASE_CHARSET: utf8mb4
      MYSQL_DATABASE_COLLATION: utf8mb4_unicode_ci
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: usuario
      PMA_PASSWORD: senha
    depends_on:
      - db

volumes:
  db_data: